version: "3.8"

services:
    kokunime-web:
        container_name: kokunime-web
        build:
            context: .
            dockerfile: Dockerfile
        image: kokunime:latest
        restart: always
        ports:
            - 4000:3000
        env_file: .env
        environment:
            NEXT_PUBLIC_KUSONIME_API: "https://brick-red-cricket-gown.cyclic.app/api"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
